# global application configs
spring.application.name=upload-service

# Multipart File Upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# AWS specific configs (to be replaced with environment variables in prod)
app.aws.s3.bucket-name=my-app-uploads
app.aws.sqs.queue-name=file-processing-queue
